### ISSUE TITLE
List of To-Do

### ISSUE THREAD

**Issue by JamsRepos** [JamsRepos/Jamfin#5]
- [x] Change README  "Screenshots" link to navigate to`#-screenshots`.
- [x] Include the moving cards in the complete pack.
- [x] #8
- [x] Add design reference of Scyfin. 
- [x] #6
